language: bash

services:
  - docker

before_script:
  - docker build . --tag=sapi-r-client

script:
  - docker run -e KBC_TEST_TOKEN -e KBC_TEST_URL sapi-r-client /code/check.sh

notifications:
  slack:
    secure: SyTfH8QglK5g/0/pdy8a1PVP6TUa8LS98wha57B7UoYUlEY3img/xQmwa6AyrjCYBiHV4gJEHNeR1f8qVO6f6jNHvn6qBn3d9xVkdD8zj8CZoQMbYVgffR3ZEoQuxwWSD5tV41O7PS2fQShtVQ5L4QExPXK+tlAZ45IJpQSagUVrKjneVM18dzk7mPBki03VssxegayzuUS6048iEnCtXapg0v3jRo/np3RwWngT8yqXZrt093f0sds5dCRPEwrLzahyTsZ+0T4luMflpaGMeqndqiZaRMKsvD6es+velkKs1KibebrZ8KerYiXyAckRh2A0+dGExjVFH2xQhtbB2ajfDyUQobTJPWKwMKlymtD8A1J1SFnTbn1q1sSvgwG2aq/8ZxKgvV1hPcfssZedk1vcl80VCkYqsYX1N0VJhvofCFIVJ11iAmV5PQZLvOOxrx5lo9I0d72xp06RBmfVDeNSnxXL9k4UwPJz6ykF5gUc5W3qw0pO4ExPHXE8nqVnVFGo7kOwj38KUqgC3kjL99wKAP6z1Mqno5eJUGUQhXGxaaCdXz76461MMmbFcD9fzCqGjYcN66RakliQvCnOoxYqLYblov5zSL7YTMygblcNaAH8FRyIo3dhoHEsQJ7PNEDl7zj1o0schFZyA0qiV8QLdwGiTmFdkjcNNK21viU=
  email: false
