language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
  - cloudyr/aws-signature

secure: "w8qozjMW+oJjxCREfJoMtCSrGZJ8oRooDCwaxYtCfvsIu1Atef6WGHofqYOWDHw6cx4292Z/b/qMJ85Jxi0wMGpFFOtQyR6m7N+YLJ5qyWsNcxZyaJIKfijR014HzTR0Ay435v3R6FzehZZxAKN0Y4dnuxlSvR9FV0l9e4B7e0wt49sOC+XhHZe6MQd/kTv7hYW4Mo2LLSoXgAj+quwqX1me0sjQCvVjmIlyl/p7MFK5XUZ7YSks/k/CdDOUQe2ozz2+KqyqnIMxrfScAld83JxuzSAbEEWv0Cmbd0f/Gw9yr0MxbUIpyRmFNyNkXoLnaGaOiHgkLGguYqHJ8p1mB6sCN6Y2GWzfDxHIP858NTQExYKOH4kJUuoA6sk95TcOkGBYpAbQKaH3EW1WhGfey9PnLH396Nma73xvxZuW1Lw3xG2j0mszZ3Twq4HyTXyiSZ58O70rRX+TgIaFkTTlcaCi8An8No3hq2MXebBUOGoupp9elDZpr9aBsx5g/IangYIf7/t51GJ8dYOzn/Ie+Z+e+0IrEHRbd/NUYzjH1f8vwo8ixrBDdkZABJ9W7SN2SmNZ4yZNcblw+DPA9qTxi8B7y5GPaYYjLeV+gbYiH9zVfVzIn5KA8F7T9FtVrPQB9PRCjPF4sa3ZI+l079LKqC2yXmtQtYnyxFRH6IQFOjk="